__author__ = 'franciscoarcecardenas'
contextactivities = {
              '/activity/POO':[":5984/objetos/objetos/clases.jpg,play,imagen,1",":5984/objetos/objetos/descarga.jpg,play,imagen,2"],
              '/activity/Historia': [{'url': ':5984/objetos/objetos/a1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                     {'url': ':5984/objetos/objetos/m1.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                     {'url': ':5984/objetos/objetos/b1.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                     {'url': ':5984/objetos/objetos/a2.jpg', 'estado': 'play', 'dispositivo': '4', 'tipo': 'imagen'} ,
                                     {'url': ':5984/objetos/objetos/m2.jpg', 'estado': 'play', 'dispositivo': '5', 'tipo': 'imagen'} ,
                                     {'url': ':5984/objetos/objetos/b2.jpg', 'estado': 'play', 'dispositivo': '6', 'tipo': 'imagen'} ,
                                     {'url': ':5984/objetos/objetos/a3.jpg', 'estado': 'play', 'dispositivo': '7', 'tipo': 'imagen'} ,
                                     {'url': ':5984/objetos/objetos/m3.jpg', 'estado': 'play', 'dispositivo': '8', 'tipo': 'imagen'} ,
                                     {'url': ':5984/objetos/objetos/b3.jpg', 'estado': 'play', 'dispositivo': '9', 'tipo': 'imagen'}],

              '/activity/Historia1': [{'url': ':5984/objetos/objetos/a1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                      {'url': ':5984/objetos/objetos/m1.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                      {'url': ':5984/objetos/objetos/b1.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                      {'url': ':5984/objetos/objetos/historia.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Historia2': [{'url': ':5984/objetos/objetos/a2.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/m2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/b2.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/historia.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Historia3': [{'url': ':5984/objetos/objetos/a3.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/m3.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/b3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'},
                                        {'url': ':5984/objetos/objetos/historia.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Autores': [{'url': ':5984/objetos/objetos/ep1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/em1.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/ep2.jpg', 'estado': 'play', 'dispositivo': '4', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/em2.jpg', 'estado': 'play', 'dispositivo': '5', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '6', 'tipo': 'audio'} ,
                                    {'url': ':5984/objetos/objetos/ep3.jpg', 'estado': 'play', 'dispositivo': '7', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/em3.jpg', 'estado': 'play', 'dispositivo': '8', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '9', 'tipo': 'audio'}],

              '/activity/Letra': [{'url': ':5984/objetos/objetos/le1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hi1.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hnm1.mp3', 'estado': 'play', 'dispositivo': '3', 'tipo': 'audio'} ,
                                    {'url': ':5984/objetos/objetos/le2.jpg', 'estado': 'play', 'dispositivo': '4', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hi2.jpg', 'estado': 'play', 'dispositivo': '5', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hnm2.mp3', 'estado': 'play', 'dispositivo': '6', 'tipo': 'audio'} ,
                                    {'url': ':5984/objetos/objetos/le3.jpg', 'estado': 'play', 'dispositivo': '7', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hi3.jpg', 'estado': 'play', 'dispositivo': '8', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hnm3.mp3', 'estado': 'play', 'dispositivo': '9', 'tipo': 'audio'} ],

              '/activity/Letra1': [{'url': ':5984/objetos/objetos/le1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hi1.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/le1.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hnm1.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Letra2': [{'url': ':5984/objetos/objetos/le2.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hi2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/le2.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hnm2.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Letra3': [{'url': ':5984/objetos/objetos/le2.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hi3.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/le2.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                    {'url': ':5984/objetos/objetos/hnm3.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Autores1': [{'url': ':5984/objetos/objetos/bo1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pe1.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                                        {'url': ':5984/objetos/objetos/bo2.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pe2.jpg', 'estado': 'play', 'dispositivo': '5', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '6', 'tipo': 'audio'} ,
                                        {'url': ':5984/objetos/objetos/bo3.jpg', 'estado': 'play', 'dispositivo': '7', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pe3.jpg', 'estado': 'play', 'dispositivo': '8', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '9', 'tipo': 'audio'} ,],

              '/activity/Autores11': [{'url': ':5984/objetos/objetos/le2.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pe1.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/le2.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/autores1.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Autores12': [{'url': ':5984/objetos/objetos/bo2.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pe2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/bo2.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/autores1.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Autores13': [{'url': ':5984/objetos/objetos/bo3.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pe3.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/bo3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/autores1.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Autores2': [{'url': ':5984/objetos/objetos/ja1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pa1.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '3', 'tipo': 'audio'} ,
                                        {'url': ':5984/objetos/objetos/ja2.jpg', 'estado': 'play', 'dispositivo': '4', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pa2.jpg', 'estado': 'play', 'dispositivo': '5', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '6', 'tipo': 'audio'} ,
                                        {'url': ':5984/objetos/objetos/ja3.jpg', 'estado': 'play', 'dispositivo': '7', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pa3.jpg', 'estado': 'play', 'dispositivo': '8', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '9', 'tipo': 'audio'} ,],

              '/activity/Autores21': [{'url': ':5984/objetos/objetos/ja1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pa1.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/ja1.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/autores2.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Autores22': [{'url': ':5984/objetos/objetos/ja2.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pa2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/ja2.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/autores2.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Autores23': [{'url': ':5984/objetos/objetos/ja3.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/pa3.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/ja3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/autores2.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Uso': [{'url': ':5984/objetos/objetos/uso1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/uso2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/uso1.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/uso.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Ensenanza': [{'url': ':5984/objetos/objetos/ens1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/ens2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/ens1.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/ensenansa.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Otrosidiomas': [{'url': ':5984/objetos/objetos/idio1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/idio2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/idio1.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/idiomas.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Importancia': [{'url': ':5984/objetos/objetos/imp1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/imp2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/imp1.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/importancia.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Cine': [{'url': ':5984/objetos/objetos/cine1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/cine2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/cine3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/cine.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Curiosidades': [{'url': ':5984/objetos/objetos/curio1.jpg', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/curio2.jpg', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/curio3.jpg', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                        {'url': ':5984/objetos/objetos/curiosidades.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/activity/Karaoke':[{'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                                   {'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                                   {'url': ':5984/objetos/objetos/himno.mp4', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,
                                   {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,],

              '/test/test':[{'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '1', 'tipo': 'imagen'} ,
                            {'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '2', 'tipo': 'imagen'} ,
                             {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                              {'url': ':5984/objetos/objetos/loading.gif', 'estado': 'play', 'dispositivo': '3', 'tipo': 'imagen'} ,],


              '/test/pretest':[{'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '1', 'tipo': 'audio'} ,
                            {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '2', 'tipo': 'audio'} ,
                             {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '4', 'tipo': 'audio'} ,
                            {'url': ':5984/objetos/objetos/nosound.mp3', 'estado': 'play', 'dispositivo': '3', 'tipo': 'audio'} ,],
              '/woutobjects':[ ],
             }